"""Shared configuration for the ForkCast restaurant-chain analytics project.

Harbor & Hearth Kitchen is a fictional 6-unit upscale-casual chain in South Florida.
All data is synthetic, generated by `generate_data.py`, but the drivers behind it
(seasonality, Florida minimum-wage steps, protein inflation, a menu price increase,
a new store ramping up) mirror what a real operator would see.
"""
from pathlib import Path
from datetime import date

ROOT = Path(__file__).resolve().parents[1]
RAW = ROOT / "data" / "raw"
MARTS = ROOT / "data" / "marts"
WAREHOUSE = ROOT / "data" / "forkcast.duckdb"
SQL_DIR = ROOT / "sql"
DASHBOARD_DIR = ROOT / "dashboard"

SEED = 42
START = date(2024, 9, 1)
END = date(2026, 8, 31)          # 24 full months of history
FORECAST_MONTHS = 12             # Sep 2026 - Aug 2027

CHAIN_NAME = "Harbor & Hearth Kitchen"

# Florida minimum wage (Amendment 2): steps up every Sept 30; tipped wage = min - 3.02
MIN_WAGE_STEPS = [
    (date(2023, 9, 30), 12.00),
    (date(2024, 9, 30), 13.00),
    (date(2025, 9, 30), 14.00),
    (date(2026, 9, 30), 15.00),
]
TIP_CREDIT = 3.02
PAYROLL_BURDEN = 0.12            # employer taxes + benefits on top of wages

MENU_PRICE_INCREASE_DATE = date(2026, 1, 15)
MENU_PRICE_INCREASE = 0.04


def min_wage_on(d: date) -> float:
    wage = MIN_WAGE_STEPS[0][1]
    for step_date, w in MIN_WAGE_STEPS:
        if d >= step_date:
            wage = w
    return wage
